<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search Button_attachment-full size-full</name>
   <tag></tag>
   <elementGuidId>e3edfed2-501c-474f-8d82-cd34189f107c</elementGuidId>
   <imagePath>../../Desktop/banner.jpg</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/section/div/div/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../../Desktop/banner.jpg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>4808</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.choucairtesting.com/wp-content/uploads/2019/07/banner.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://www.choucairtesting.com/wp-content/uploads/2019/07/banner.png 4808w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-300x75.png 300w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-768x192.png 768w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-1024x256.png 1024w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-640x160.png 640w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-830x207.png 830w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-230x57.png 230w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-350x87.png 350w, https://www.choucairtesting.com/wp-content/uploads/2019/07/banner-480x120.png 480w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 4808px) 100vw, 4808px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container content-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;elementor elementor-344&quot;]/div[@class=&quot;elementor-inner&quot;]/div[@class=&quot;elementor-section-wrap&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-3634740 elementor-section-stretched elementor-section-full_width elementor-section-height-min-height elementor-section-height-default elementor-section-items-middle&quot;]/div[@class=&quot;elementor-container elementor-column-gap-no&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-ecb8a67&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/div[@class=&quot;elementor-element elementor-element-986a803 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image&quot;]/img[@class=&quot;attachment-full size-full&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/section/div/div/div/div/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.choucairtesting.com/wp-content/uploads/2019/07/banner.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
